# **Image Transformation**

In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread("Input/flemingo.jpg")

In [3]:
# Display function
def display(winname, img):
    cv2.imshow(winname, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [4]:
display("flemingo", img)

## Translation or Shifting

In [5]:
tx = 100 # shift right side
ty = 150 # shift downward
M = np.float32([[1, 0, tx], 
                [0, 1, ty]])
print(M)

[[  1.   0. 100.]
 [  0.   1. 150.]]


In [6]:
shifted_img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))

# img.shape[1] : image width (x)
# img.shape[0] : image height (y)
# remember : img.shape => (height, width, channel)

In [7]:
display("shifted image", shifted_img)

In [8]:
# Create translation function and display it
def translation(img, tx, ty):
    M = np.float32([[1, 0, tx], 
                    [0, 1, ty]])
    shifted_img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
    display("shifted image", shifted_img)
    cv2.imwrite("Output/shifted image.png", shifted_img)

In [9]:
translation(img, -50, -100)

## Rotation

In [11]:
# Determine center point for rotation
center = (img.shape[1]//2, img.shape[0]//2)

In [12]:
M = cv2.getRotationMatrix2D(center, 60, 1) # (center point, degree rotation, scale)
M

array([[   0.5       ,    0.8660254 , -117.12812921],
       [  -0.8660254 ,    0.5       ,  437.12812921]])

In [13]:
rotate_60 = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))

In [14]:
display("rotate 60 degree", rotate_60)

In [29]:
# Create rotation function
def rotate(img, angle, scale):
    center = (img.shape[1]//2, img.shape[0]//2)
    M = cv2.getRotationMatrix2D(center, angle, scale)
    rotate_img = cv2.warpAffine(img, M, (img.shape[1], img.shape[0]))
    cv2.imwrite("Output/rotate image.png", rotate_img)

    display(f"rotate image {angle} degree", rotate_img)

In [30]:
rotate(img, -15, 0.75)

## Resize

In [25]:
img.shape

(640, 640, 3)

In [35]:
img_resize = cv2.resize(img, (400,300), interpolation=cv2.INTER_AREA)

In [36]:
img_resize.shape

(300, 400, 3)

In [37]:
cv2.imshow("original", img)
cv2.imshow("resize", img_resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
cv2.imwrite("Output/resize image.png", img_resize)

True

## Flipping

In [41]:
flip_img_1 = cv2.flip(img, 1) # horizontal flip
flip_img_min1 = cv2.flip(img, -1) # horizontal and vertical flip at the same time
flip_img_0 = cv2.flip(img, 0) # vertical flip

In [42]:
cv2.imshow("original", img)
cv2.imshow("horizontal flip", flip_img_1)
cv2.imshow("horizontal and vertical flip", flip_img_min1)
cv2.imshow("vertical flip", flip_img_0)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
cv2.imwrite("Output/flip image.png", flip_img_min1)

True

## Cropping

In [55]:
crop = img[200:300, 100:500] # rows_pixel, cols_pixel

In [56]:
display("crop", crop)

In [57]:
cv2.imwrite("Output/crop image.png", crop)

True